version: "3.9"

services:
  skillshub-front:
    build:
      context: .
    ports:
      - "5173:80"
    container_name: skillshub-front
    restart: unless-stopped
    environment:
      VITE_KEYCLOAK_URL: "https://auth.skillshub.com"
      VITE_KEYCLOAK_REALM: "skillshub"
      VITE_KEYCLOAK_CLIENT_ID: "frontend-skillshub"
      VITE_API_URL: "https://api.skillshub.com"
