version: "3.9"

services:
  skillshub-front-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: skillshub-front-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_KEYCLOAK_URL=http://localhost:8080
      - VITE_KEYCLOAK_REALM=skillshub
      - VITE_KEYCLOAK_CLIENT_ID=frontend-skillshub
      - VITE_API_URL=http://localhost:10020/api
    command: [ "npm", "run", "dev" ]