services:
  skillshub-front:
    build:
      context: .
    container_name: skillshub-front
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - ./env/dev/local-gateway.env
